### ISSUE TITLE
求筆劃輸入法

### ISSUE THREAD

**Issue by WingCH** [chinese-opendesktop/cin-tables#2]
請問有筆劃輸入法的cin檔嗎

**Comment by bluebat** [comment]
請看看 stroke5.cin, bsm.cin, g6code.cin 之中是否有適用的？

**Comment by WingCH** [comment]
g6code.cin 是類似了 但是頭三尾三的筆劃碼，不是傳統全碼的筆劃輸入法，但是也謝謝你的拹助~

**Comment by bluebat** [comment]
或許 https://github.com/chinese-opendesktop/cns11643-data 專案中的 collation/cns11643_stroke.txt
可以參考一下。
