### ISSUE TITLE
双拼用户，想求自然码方案，或者自己动手转个自然码词库出来，请问从何做起

### ISSUE THREAD

**Issue by dsalk** [chinese-opendesktop/cin-tables#3]

**Comment by bluebat** [comment]
請參考 ziranma.cin

**Comment by dsalk** [comment]
谢指出方向。
直接找到的[ziranma.cin](https://github.com/jwiegley/emacs-release/blob/master/leim/MISC-DIC/ziranma.cin)导入失败，参照另一份可用的[ms-shuangpin.cin](https://github.com/Windfarer/ms-shuangpin.cin)修改了一下后已经可以使用。
不过只能说可以凑活，官方方案路漫漫啊......

**Comment by bluebat** [comment]
本專案中的 https://github.com/chinese-opendesktop/cin-tables/blob/master/ziranma.cin 也不適用嗎？
