### ISSUE TITLE
大易3碼表缺字

### ISSUE THREAD

**Issue by internlin** [chinese-opendesktop/cin-tables#4]
您好，我在測試 pime 時，意外發現大易3碼有缺字

tf8 應該還要有「續」才對，目前只有「績、纈」這兩個字，還煩請更改，謝謝！

P.s 是否也可請您校對一下大易三碼表，是否還有其類似漏字情形呢，大感謝！

**Comment by internlin** [comment]
再補充 「綾」 這個字的大易三碼，也是 tf8 ，謝謝您！

**Comment by bluebat** [comment]
大易我不熟 :) 查詢 dayi3.cin 檔案，目前已有：
t8 續
tfx 綾
似乎少了「tf8 續」，但「綾」應該就是 tfx 吧？

**Comment by internlin** [comment]
抱歉，是我眼花...  囧
「綾」是 tfx 沒錯  Orz

**Comment by internlin** [comment]
抱歉，是我眼花...  囧
「綾」是 tfx 沒錯，謝謝  Orz
