### ISSUE TITLE
CIN in active use

### ISSUE THREAD

**Issue by lxs602** [chinese-opendesktop/cin-tables#6]
Hi,

I have a question. 

Do you know if any of these input methods are obsolete / deprecated?

Also, is Big-5 commonly used as an input method? I have only ever heard of it as a character encoding (e.g. UTF-8, gb2312, etc.)

I am beginning to learn Chinese. I hope English is ok.

謝謝,

路加

**Comment by bluebat** [comment]
For traditional Chinese input, AFAIK, most people use Bopomofo(注音), some use CangJie(倉頡), very few use 4Corner, Array, Dayi, Boshiamy, and others are obsolete/deprecated/unusable.
Character encodings are not for normal input, only for reference or characters not included in tables.
